name: Sync to Language Repositories

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      
      - name: Sync to Irish Repository
        run: |
          git remote add gaeilge https://${{ secrets.FOCLOIR_TOKEN }}@github.com/angeidheal/foclóir-na-ngaylgeoirí.git
          git push gaeilge main
      
      - name: Sync to Manx Repository
        run: |
          git remote add gaelg https://${{ secrets.FOCLOIR_TOKEN }}@github.com/angeidheal/fockleyr-ny-gailgeyryn.git
          git push gaelg main 